export default {
    kind: "customsearch#search",
    url: {
        type: "application/json",
        template: "https://www.googleapis.com/customsearch/v1?q={searchTerms}&num={count?}&start={startIndex?}&lr={language?}&safe={safe?}&cx={cx?}&sort={sort?}&filter={filter?}&gl={gl?}&cr={cr?}&googlehost={googleHost?}&c2coff={disableCnTwTranslation?}&hq={hq?}&hl={hl?}&siteSearch={siteSearch?}&siteSearchFilter={siteSearchFilter?}&exactTerms={exactTerms?}&excludeTerms={excludeTerms?}&linkSite={linkSite?}&orTerms={orTerms?}&relatedSite={relatedSite?}&dateRestrict={dateRestrict?}&lowRange={lowRange?}&highRange={highRange?}&searchType={searchType}&fileType={fileType?}&rights={rights?}&imgSize={imgSize?}&imgType={imgType?}&imgColorType={imgColorType?}&imgDominantColor={imgDominantColor?}&alt=json",
    },
    queries: {
        request: [{
            title: "Google Custom Search - linkedin",
            totalResults: "171000000",
            searchTerms: "linkedin",
            count: 10,
            startIndex: 1,
            inputEncoding: "utf8",
            outputEncoding: "utf8",
            safe: "off",
            cx: "444f6b0bc85e819cd",
        }, ],
        nextPage: [{
            title: "Google Custom Search - linkedin",
            totalResults: "171000000",
            searchTerms: "linkedin",
            count: 10,
            startIndex: 11,
            inputEncoding: "utf8",
            outputEncoding: "utf8",
            safe: "off",
            cx: "444f6b0bc85e819cd",
        }, ],
    },
    context: {
        title: "Google",
    },
    searchInformation: {
        searchTime: 0.404447,
        formattedSearchTime: "0.40",
        totalResults: "171000000",
        formattedTotalResults: "171,000,000",
    },
    items: [{
            kind: "customsearch#result",
            title: "Waymo | LinkedIn",
            htmlTitle: "Waymo | <b>LinkedIn</b>",
            link: "https://www.google.com/appserve/mkt/p/AFnwnKVdHyykT1OIIO62s4tHSzIqfzQpAqBPFWFxOZHS2zLueCseoEtv2St_m7pknDMC-V1durutB9dZerJycaE_9aKr-ztry7cecHorBslddjhk1yevF16bpcvw",
            displayLink: "www.google.com",
            snippet: "Waymo | 101831 followers on LinkedIn. Waymo is an autonomous driving \ntechnology company creating a new way forward in mobility. | Waymo is an ...",
            htmlSnippet: "Waymo | 101831 followers on <b>LinkedIn</b>. Waymo is an autonomous driving <br>\ntechnology company creating a new way forward in mobility. | Waymo is an&nbsp;...",
            formattedUrl: "https://www.google.com/.../ AFnwnKVdHyykT1OIIO62s4tHSzIqfzQpAqBPFWFxOZHS2zLueCseoEtv...",
            htmlFormattedUrl: "https://www.google.com/.../ AFnwnKVdHyykT1OIIO62s4tHSzIqfzQpAqBPFWFxOZHS2zLueCseoEtv...",
            pagemap: {
                cse_thumbnail: [{
                    src: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRr-UZOCD7V7HwKGrrZNw7XgQ_kb6fgpcldwEbZmtLt5XbJ4bMvSy_u2pA",
                    width: "200",
                    height: "200",
                }, ],
                metatags: [{
                    "og:image": "https://media-exp1.licdn.com/dms/image/C4E0BAQG4FdRM0dx-3w/company-logo_200_200/0/1519864577171?e=2159024400&v=beta&t=xWi6YprRZSenfageETFsI2r88YK9O1sTr9pRzTYjF5U",
                    "og:type": "article",
                    "twitter:card": "summary",
                    "twitter:title": "Waymo | LinkedIn",
                    "al:ios:app_name": "LinkedIn",
                    "og:title": "Waymo | LinkedIn",
                    "al:android:package": "com.linkedin.android",
                    pagekey: "p_org_guest_company_overview",
                    locale: "en_US",
                    "al:ios:url": "https://www.linkedin.com/company/waymo",
                    "og:description": "Waymo | 101,831 followers on LinkedIn. Waymo is an autonomous driving technology company creating a new way forward in mobility. | Waymo is an autonomous driving technology company with a mission to make it safe and easy for people and things to move around. With the Waymo Driver, we can improve the world’s mobility while saving thousands of lives.\n\nWaymo reaches out to candidates from official channels only (e.g. directly from @waymo.com email addresses, or through our recruiters or sourcers who are noted as such on LinkedIn).",
                    "al:ios:app_store_id": "288429040",
                    "twitter:image": "https://media-exp1.licdn.com/dms/image/C4E0BAQG4FdRM0dx-3w/company-logo_200_200/0/1519864577171?e=2159024400&v=beta&t=xWi6YprRZSenfageETFsI2r88YK9O1sTr9pRzTYjF5U",
                    "al:android:url": "https://www.linkedin.com/company/waymo",
                    "twitter:site": "@linkedin",
                    viewport: "width=device-width, initial-scale=1.0",
                    "twitter:description": "Waymo | 101,831 followers on LinkedIn. Waymo is an autonomous driving technology company creating a new way forward in mobility. | Waymo is an autonomous driving technology company with a mission to make it safe and easy for people and things to move around. With the Waymo Driver, we can improve the world’s mobility while saving thousands of lives.\n\nWaymo reaches out to candidates from official channels only (e.g. directly from @waymo.com email addresses, or through our recruiters or sourcers who are noted as such on LinkedIn).",
                    "og:url": "https://www.linkedin.com/company/waymo",
                    "al:android:app_name": "LinkedIn",
                }, ],
                cse_image: [{
                    src: "https://media-exp1.licdn.com/dms/image/C4E0BAQG4FdRM0dx-3w/company-logo_200_200/0/1519864577171?e=2159024400&v=beta&t=xWi6YprRZSenfageETFsI2r88YK9O1sTr9pRzTYjF5U",
                }, ],
            },
        },
        {
            kind: "customsearch#result",
            title: "Google Cloud | LinkedIn",
            htmlTitle: "Google Cloud | <b>LinkedIn</b>",
            link: "https://www.google.com/appserve/mkt/p/AIQrb_4cS-v-0XWZAZUqm0XHw3BEfAsRLRmsaZlX2S3QAJxSwX0k3qB34CJ_DugB06cPVxbwuVEaIEpPzfJETnKrNRY6pfzOb1aO5e8mQ_GhHVQ",
            displayLink: "www.google.com",
            snippet: "Google Cloud | 1168508 followers on LinkedIn. Find out how computing power \ndelivered everywhere, for everyone, is transforming business with GCP, G Suite,\n ...",
            htmlSnippet: "Google Cloud | 1168508 followers on <b>LinkedIn</b>. Find out how computing power <br>\ndelivered everywhere, for everyone, is transforming business with GCP, G Suite,<br>\n&nbsp;...",
            formattedUrl: "https://www.google.com/.../AIQrb_4cS-v- 0XWZAZUqm0XHw3BEfAsRLRmsaZlX2S3QAJxSwX0k3qB34CJ_ ...",
            htmlFormattedUrl: "https://www.google.com/.../AIQrb_4cS-v- 0XWZAZUqm0XHw3BEfAsRLRmsaZlX2S3QAJxSwX0k3qB34CJ_ ...",
            pagemap: {
                cse_thumbnail: [{
                    src: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcS4crvGaImig0dyUhaAjJTED7EpX3r3u5nrfXTH4DocKqY77FAw515r_cnN",
                    width: "200",
                    height: "200",
                }, ],
                metatags: [{
                    "og:image": "https://media-exp1.licdn.com/dms/image/C560BAQFIFLR7jxm2lg/company-logo_200_200/0/1600274556510?e=2159024400&v=beta&t=QBYLM-a07my5phjCBhts4yMKaUUviEOdh-Mgf_UgoFE",
                    "og:type": "article",
                    "twitter:card": "summary",
                    "twitter:title": "Google Cloud | LinkedIn",
                    "al:ios:app_name": "LinkedIn",
                    "og:title": "Google Cloud | LinkedIn",
                    "al:android:package": "com.linkedin.android",
                    pagekey: "p_org_guest_showcase_overview",
                    locale: "en_US",
                    "al:ios:url": "https://www.linkedin.com/showcase/google-cloud",
                    "og:description": "Google Cloud | 1,168,508 followers on LinkedIn. Find out how computing power delivered everywhere, for everyone, is transforming business with GCP, G Suite, Google Maps API, and Chrome & Android devices.",
                    "al:ios:app_store_id": "288429040",
                    "twitter:image": "https://media-exp1.licdn.com/dms/image/C560BAQFIFLR7jxm2lg/company-logo_200_200/0/1600274556510?e=2159024400&v=beta&t=QBYLM-a07my5phjCBhts4yMKaUUviEOdh-Mgf_UgoFE",
                    "al:android:url": "https://www.linkedin.com/showcase/google-cloud",
                    "twitter:site": "@linkedin",
                    viewport: "width=device-width, initial-scale=1.0",
                    "twitter:description": "Google Cloud | 1,168,508 followers on LinkedIn. Find out how computing power delivered everywhere, for everyone, is transforming business with GCP, G Suite, Google Maps API, and Chrome & Android devices.",
                    "og:url": "https://www.linkedin.com/showcase/google-cloud",
                    "al:android:app_name": "LinkedIn",
                }, ],
                cse_image: [{
                    src: "https://media-exp1.licdn.com/dms/image/C560BAQFIFLR7jxm2lg/company-logo_200_200/0/1600274556510?e=2159024400&v=beta&t=QBYLM-a07my5phjCBhts4yMKaUUviEOdh-Mgf_UgoFE",
                }, ],
            },
        },
        {
            kind: "customsearch#result",
            title: "Google Ads | LinkedIn",
            htmlTitle: "Google Ads | <b>LinkedIn</b>",
            link: "https://www.google.com/appserve/mkt/p/ABMBUQOlQzu_1JbJD6osxsgFXITBiCh3M6r5RXUPjNNrsFFXzc5RXnmWL4rAwV4hTR7sTZMgdj6bFq-mwfG9oAcrgvE-Kuojserl2jL_nDmlDdziBAKOJE6m52MSxCyi7UHzGGN4MY-QZAXLCGJDzdsPUP2jPNIXsGbcQG4SF2Y264KcvWB7nghG",
            displayLink: "www.google.com",
            snippet: "Google Ads | 486221 followers on LinkedIn. The official page for updates, tips, \nand inspiration from the Google Ads team. | The official page for updates, tips, \nand ...",
            htmlSnippet: "Google Ads | 486221 followers on <b>LinkedIn</b>. The official page for updates, tips, <br>\nand inspiration from the Google Ads team. | The official page for updates, tips, <br>\nand&nbsp;...",
            formattedUrl: "https://www.google.com/.../ABMBUQOlQzu_ 1JbJD6osxsgFXITBiCh3M6r5RXUPjNNrsFFXzc5RXnmWL4rAwV4hTR7s...",
            htmlFormattedUrl: "https://www.google.com/.../ABMBUQOlQzu_ 1JbJD6osxsgFXITBiCh3M6r5RXUPjNNrsFFXzc5RXnmWL4rAwV4hTR7s...",
            pagemap: {
                cse_thumbnail: [{
                    src: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSv2vlBM2ePRaLpe5l0weH0V4_nlsIwMn3tpiD6fV4UtuBQXCEQfCBFMPhE",
                    width: "200",
                    height: "200",
                }, ],
                metatags: [{
                    "og:image": "https://media-exp3.licdn.com/dms/image/C560BAQH9F59ob8d3QQ/company-logo_200_200/0/1532457874219?e=2159024400&v=beta&t=3WSLapk-AMGZbjl5dnVZ6IAShwqsTscqV1JjBqSov7g",
                    "og:type": "article",
                    "twitter:card": "summary",
                    "twitter:title": "Google Ads | LinkedIn",
                    "al:ios:app_name": "LinkedIn",
                    "og:title": "Google Ads | LinkedIn",
                    "al:android:package": "com.linkedin.android",
                    pagekey: "p_org_guest_showcase_overview",
                    locale: "en_US",
                    "al:ios:url": "https://www.linkedin.com/showcase/google-ads-",
                    "og:description": "Google Ads | 486,221 followers on LinkedIn. The official page for updates, tips, and inspiration from the Google Ads team. | The official page for updates, tips, and inspiration from the Google Ads team.\n\n📣 Official Google Ads blog → http://goo.gle/2OGIJ24\n👥 Google Ads Help Community → http://goo.gle/3t2opqD\n📘 Google Ads Help Center  → http://goo.gle/3rw69Wr",
                    "al:ios:app_store_id": "288429040",
                    "twitter:image": "https://media-exp3.licdn.com/dms/image/C560BAQH9F59ob8d3QQ/company-logo_200_200/0/1532457874219?e=2159024400&v=beta&t=3WSLapk-AMGZbjl5dnVZ6IAShwqsTscqV1JjBqSov7g",
                    "al:android:url": "https://www.linkedin.com/showcase/google-ads-",
                    "twitter:site": "@linkedin",
                    viewport: "width=device-width, initial-scale=1.0",
                    "twitter:description": "Google Ads | 486,221 followers on LinkedIn. The official page for updates, tips, and inspiration from the Google Ads team. | The official page for updates, tips, and inspiration from the Google Ads team.\n\n📣 Official Google Ads blog → http://goo.gle/2OGIJ24\n👥 Google Ads Help Community → http://goo.gle/3t2opqD\n📘 Google Ads Help Center  → http://goo.gle/3rw69Wr",
                    "og:url": "https://www.linkedin.com/showcase/google-ads-",
                    "al:android:app_name": "LinkedIn",
                }, ],
                cse_image: [{
                    src: "https://media-exp3.licdn.com/dms/image/C560BAQH9F59ob8d3QQ/company-logo_200_200/0/1532457874219?e=2159024400&v=beta&t=3WSLapk-AMGZbjl5dnVZ6IAShwqsTscqV1JjBqSov7g",
                }, ],
            },
        },
        {
            kind: "customsearch#result",
            title: "Google Ad Manager | LinkedIn",
            htmlTitle: "Google Ad Manager | <b>LinkedIn</b>",
            link: "https://www.google.com/appserve/mkt/p/APDk4sNfotWJBplNvWxSr6REyDByzY9w5PLibCqOWN0mEAgm89lyICdXasGYKT4wLtg9Fl80LdAWTCyF5BxPxXBEYHDOGvWHLDnwkIQdEC3gEdY2Nk7pl8rSfTwYHHiog8uuc6FWgHNN3w",
            displayLink: "www.google.com",
            snippet: "Google Ad Manager | 156454 followers on LinkedIn. Google Ad Manager is a \ncomplete platform to grow all of your digital ad revenues and protect your brand \nin ...",
            htmlSnippet: "Google Ad Manager | 156454 followers on <b>LinkedIn</b>. Google Ad Manager is a <br>\ncomplete platform to grow all of your digital ad revenues and protect your brand <br>\nin&nbsp;...",
            formattedUrl: "https://www.google.com/.../ APDk4sNfotWJBplNvWxSr6REyDByzY9w5PLibCqOWN0mEAgm89lyIC...",
            htmlFormattedUrl: "https://www.google.com/.../ APDk4sNfotWJBplNvWxSr6REyDByzY9w5PLibCqOWN0mEAgm89lyIC...",
            pagemap: {
                cse_thumbnail: [{
                    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwt6BW38nWdWnmD8v47wemrJxHzZBgmEiM7AYkPvs2z782vLIt-_OKYUZ0",
                    width: "200",
                    height: "200",
                }, ],
                metatags: [{
                    "og:image": "https://media-exp1.licdn.com/dms/image/C4D0BAQGw17ewnMox_w/company-logo_200_200/0/1530072756934?e=2159024400&v=beta&t=Q3J3MJgpEVu9_yVVH1XD24vqUFbbfwD2Q4tlntC4a8Y",
                    "og:type": "article",
                    "twitter:card": "summary",
                    "twitter:title": "Google Ad Manager | LinkedIn",
                    "al:ios:app_name": "LinkedIn",
                    "og:title": "Google Ad Manager | LinkedIn",
                    "al:android:package": "com.linkedin.android",
                    pagekey: "p_org_guest_showcase_overview",
                    locale: "en_US",
                    "al:ios:url": "https://www.linkedin.com/showcase/google-ad-manager",
                    "og:description": "Google Ad Manager | 156,454 followers on LinkedIn. Google Ad Manager is a complete platform to grow all of your digital ad revenues and protect your brand in all the new ways and places people are watching, playing, and engaging. Our unified platform leverages Google technology to help you run your business more efficiently and keep your brand protected.",
                    "al:ios:app_store_id": "288429040",
                    "twitter:image": "https://media-exp1.licdn.com/dms/image/C4D0BAQGw17ewnMox_w/company-logo_200_200/0/1530072756934?e=2159024400&v=beta&t=Q3J3MJgpEVu9_yVVH1XD24vqUFbbfwD2Q4tlntC4a8Y",
                    "al:android:url": "https://www.linkedin.com/showcase/google-ad-manager",
                    "twitter:site": "@linkedin",
                    viewport: "width=device-width, initial-scale=1.0",
                    "twitter:description": "Google Ad Manager | 156,454 followers on LinkedIn. Google Ad Manager is a complete platform to grow all of your digital ad revenues and protect your brand in all the new ways and places people are watching, playing, and engaging. Our unified platform leverages Google technology to help you run your business more efficiently and keep your brand protected.",
                    "og:url": "https://www.linkedin.com/showcase/google-ad-manager",
                    "al:android:app_name": "LinkedIn",
                }, ],
                cse_image: [{
                    src: "https://media-exp1.licdn.com/dms/image/C4D0BAQGw17ewnMox_w/company-logo_200_200/0/1530072756934?e=2159024400&v=beta&t=Q3J3MJgpEVu9_yVVH1XD24vqUFbbfwD2Q4tlntC4a8Y",
                }, ],
            },
        },
        {
            kind: "customsearch#result",
            title: "LinkedIn Corporation, 350 5th Ave, New York, NY, 10118, us ...",
            htmlTitle: "<b>LinkedIn</b> Corporation, 350 5th Ave, New York, NY, 10118, us ...",
            link: "https://www.google.com/maps/search/?api=1&query=LinkedIn+Corporation%2C+350+5th+Ave%2C+New+York%2C+NY%2C+10118%2C+us&query_place_id=ChIJFyoMrKlZwokRq7wzR_fQ740",
            displayLink: "www.google.com",
            snippet: "LinkedIn Corporation, 350 5th Ave, New York, NY, 10118, us. Connect to internet \nto see place info.",
            htmlSnippet: "<b>LinkedIn</b> Corporation, 350 5th Ave, New York, NY, 10118, us. Connect to internet <br>\nto see place info.",
            cacheId: "-Bfpc1Bt2NcJ",
            formattedUrl: "https://www.google.com/maps/search/?api=1...LinkedIn...",
            htmlFormattedUrl: "https://www.google.com/maps/search/?api=1...<b>LinkedIn</b>...",
            pagemap: {
                cse_thumbnail: [{
                    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQUDTMfgWSotdHvbOKW4AmY1steqsilnDJS4q33zGx-d0AXvvxPiFY9Mvs",
                    width: "204",
                    height: "247",
                }, ],
                metatags: [{
                    referrer: "origin",
                    "twitter:card": "summary",
                    "theme-color": "#3367d6",
                    viewport: "initial-scale=1.0, user-scalable=no",
                    google: "notranslate",
                }, ],
                cse_image: [{
                    src: "https://maps.gstatic.com/tactile/basepage/pegman_sherlock.png",
                }, ],
            },
        },
        {
            kind: "customsearch#result",
            title: "Google Play Apps & Games | LinkedIn",
            htmlTitle: "Google Play Apps &amp; Games | <b>LinkedIn</b>",
            link: "https://www.google.com/appserve/mkt/p/AFnwnKVYbeq19xplAm8BFE8iP1jK0_OhBc2J4o5tKx0WeePWDVikTyFFglB9pMLsQje0XpzqNe6rHNwqTmH2ZpST9VF-901ruXGryYhfa6dU_6YkM1M",
            displayLink: "www.google.com",
            snippet: "Jul 1, 2020 ... Google Play Apps & Games | 36157 followers on LinkedIn. Latest app and game \nupdates, news, best practices, and events from Google Play ...",
            htmlSnippet: "Jul 1, 2020 <b>...</b> Google Play Apps &amp; Games | 36157 followers on <b>LinkedIn</b>. Latest app and game <br>\nupdates, news, best practices, and events from Google Play&nbsp;...",
            formattedUrl: "https://www.google.com/.../AFnwnKVYbeq19xplAm8BFE8iP1jK0_ OhBc2J4o5tKx0WeePWDVikTyFFglB9pMLsQje0XpzqNe6rHNwqTmH2Z...",
            htmlFormattedUrl: "https://www.google.com/.../AFnwnKVYbeq19xplAm8BFE8iP1jK0_ OhBc2J4o5tKx0WeePWDVikTyFFglB9pMLsQje0XpzqNe6rHNwqTmH2Z...",
            pagemap: {
                cse_thumbnail: [{
                    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQghjIq4hzGst0z2EUf6qKA2jG4z1lmRCY_x-OojHYnLcEX2OoQLfRKTNoT",
                    width: "200",
                    height: "200",
                }, ],
                metatags: [{
                    "og:image": "https://media-exp3.licdn.com/dms/image/C510BAQF62f8Svr-aXw/company-logo_200_200/0/1519955173552?e=2159024400&v=beta&t=c3-rCr6AGl_vVSLhk0Lw37op_xFVeVUrXfO0m1hUn24",
                    "og:type": "article",
                    "twitter:card": "summary",
                    "twitter:title": "Google Play Apps & Games | LinkedIn",
                    "al:ios:app_name": "LinkedIn",
                    "og:title": "Google Play Apps & Games | LinkedIn",
                    "al:android:package": "com.linkedin.android",
                    pagekey: "p_org_guest_showcase_overview",
                    locale: "en_US",
                    "al:ios:url": "https://www.linkedin.com/showcase/googleplaydev",
                    "og:description": "Google Play Apps & Games | 36,157 followers on LinkedIn. Latest app and game updates, news, best practices, and events from Google Play Developers. // https://goo.gle/2O3bAu6 | Tips, trends, and industry thoughts for app and game developers building businesses on Google Play. \n\nFollow us on Twitter (@GooglePlayDev) and Medium.com/GooglePlayDev too.",
                    "al:ios:app_store_id": "288429040",
                    "twitter:image": "https://media-exp3.licdn.com/dms/image/C510BAQF62f8Svr-aXw/company-logo_200_200/0/1519955173552?e=2159024400&v=beta&t=c3-rCr6AGl_vVSLhk0Lw37op_xFVeVUrXfO0m1hUn24",
                    "al:android:url": "https://www.linkedin.com/showcase/googleplaydev",
                    "twitter:site": "@linkedin",
                    viewport: "width=device-width, initial-scale=1.0",
                    "twitter:description": "Google Play Apps & Games | 36,157 followers on LinkedIn. Latest app and game updates, news, best practices, and events from Google Play Developers. // https://goo.gle/2O3bAu6 | Tips, trends, and industry thoughts for app and game developers building businesses on Google Play. \n\nFollow us on Twitter (@GooglePlayDev) and Medium.com/GooglePlayDev too.",
                    "og:url": "https://www.linkedin.com/showcase/googleplaydev",
                    "al:android:app_name": "LinkedIn",
                }, ],
                cse_image: [{
                    src: "https://media-exp3.licdn.com/dms/image/C510BAQF62f8Svr-aXw/company-logo_200_200/0/1519955173552?e=2159024400&v=beta&t=c3-rCr6AGl_vVSLhk0Lw37op_xFVeVUrXfO0m1hUn24",
                }, ],
            },
        },
        {
            kind: "customsearch#result",
            title: "Google",
            htmlTitle: "Google",
            link: "https://www.google.com/",
            displayLink: "www.google.com",
            snippet: "Search the world's information, including webpages, images, videos and more. \nGoogle has many special features to help you find exactly what you're looking ...",
            htmlSnippet: "Search the world&#39;s information, including webpages, images, videos and more. <br>\nGoogle has many special features to help you find exactly what you&#39;re looking&nbsp;...",
            cacheId: "y14FcUQOGl4J",
            formattedUrl: "https://www.google.com/",
            htmlFormattedUrl: "https://www.google.com/",
            pagemap: {
                cse_thumbnail: [{
                    src: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcT3X9ZpkcNrr2kAcGZuXPZTNiK1oeTXhRMCZ1UGxNLf-an4du0eriX01mc",
                    width: "320",
                    height: "112",
                }, ],
                metatags: [{
                    referrer: "origin",
                    viewport: "width=device-width,minimum-scale=1.0",
                    google: "notranslate",
                    "format-detection": "telephone=no",
                }, ],
                cse_image: [{
                    src: "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_160x56dp.png",
                }, ],
            },
        },
        {
            kind: "customsearch#result",
            title: "Google Alerts - Monitor the Web for interesting new content",
            htmlTitle: "Google Alerts - Monitor the Web for interesting new content",
            link: "https://www.google.com/alerts",
            displayLink: "www.google.com",
            snippet: "Monitor the web for interesting new content. How often. As-it-happens. At most \nonce a day. At most once a week. Sources. Automatic. News. Blogs. Web. Video.",
            htmlSnippet: "Monitor the web for interesting new content. How often. As-it-happens. At most <br>\nonce a day. At most once a week. Sources. Automatic. News. Blogs. Web. Video.",
            cacheId: "xf92VHvV6HgJ",
            formattedUrl: "https://www.google.com/alerts",
            htmlFormattedUrl: "https://www.google.com/alerts",
            pagemap: {
                metatags: [{
                    viewport: "width=device-width, user-scalable=no",
                }, ],
            },
        },
        {
            kind: "customsearch#result",
            title: "The Technostarter",
            htmlTitle: "The Technostarter",
            link: "https://www.google.com/podcasts?feed=aHR0cHM6Ly9hbmNob3IuZm0vcy81MmY2MDIxNC9wb2RjYXN0L3Jzcw==",
            displayLink: "www.google.com",
            snippet: "She loves to write and is a regular writer on Medium and LinkedIn. . . In this \nepisode we took a deep dive into her career as a Software Engineer as well as \nthe ...",
            htmlSnippet: "She loves to write and is a regular writer on Medium and <b>LinkedIn</b>. . . In this <br>\nepisode we took a deep dive into her career as a Software Engineer as well as <br>\nthe&nbsp;...",
            cacheId: "OdaaTyHrOOYJ",
            formattedUrl: "https://www.google.com/podcasts?feed...",
            htmlFormattedUrl: "https://www.google.com/podcasts?feed...",
            pagemap: {
                metatags: [{
                    "og:image": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRtmTUh6wT-B-hXNhRqVccRlcIGAbF0MLHIPBbQ9lkoAL_MbU8",
                    "apple-itunes-app": "app-id=1398000105, affiliate-data=ct=podcastsSmartBannerShow001&pt=9008, app-argument=https://podcasts.google.com/feed/aHR0cHM6Ly9hbmNob3IuZm0vcy81MmY2MDIxNC9wb2RjYXN0L3Jzcw",
                    "og:type": "music.radio_station",
                    "twitter:card": "summary",
                    "twitter:title": "The Technostarter",
                    "og:site_name": "Google Podcasts",
                    "og:title": "The Technostarter",
                    "music:creator": "The Technostarter",
                    title: "The Technostarter",
                    "og:description": "A podcast designed to give you a dose of inspiration: featuring techno-savvy women, girls and boys from all over Canada and the Globe who are building awesome TECH, as well as, Allies who are cheering them on to greatness. We will take a deep dive into their technology adventures and life journeys creating new technologies for the good of the human race in our new super normal. Additionally, examine how they became comfortable in their own skin building great technologies for today and the future. Hosted by Irenia Roussel, Podcast Producer of the Canadian Side Hustle and Business Podcast.",
                    "twitter:creator": "The Technostarter",
                    "article:author": "The Technostarter",
                    "twitter:image": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRtmTUh6wT-B-hXNhRqVccRlcIGAbF0MLHIPBbQ9lkoAL_MbU8",
                    referrer: "origin",
                    viewport: "width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no,minimal-ui",
                    "og:url": "https://podcasts.google.com/feed/aHR0cHM6Ly9hbmNob3IuZm0vcy81MmY2MDIxNC9wb2RjYXN0L3Jzcw",
                }, ],
                cse_image: [{
                    src: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRtmTUh6wT-B-hXNhRqVccRlcIGAbF0MLHIPBbQ9lkoAL_MbU8",
                }, ],
            },
        },
        {
            kind: "customsearch#result",
            title: "gmail.co",
            htmlTitle: "gmail.co",
            link: "https://www.google.com/gmail/",
            displayLink: "www.google.com",
            snippet: "Gmail is email that's intuitive, efficient, and useful. 15 GB of storage, less spam, \nand mobile access.",
            htmlSnippet: "Gmail is email that&#39;s intuitive, efficient, and useful. 15 GB of storage, less spam, <br>\nand mobile access.",
            formattedUrl: "https://www.google.com/gmail/",
            htmlFormattedUrl: "https://www.google.com/gmail/",
            pagemap: {
                metatags: [{
                    viewport: "width=device-width, initial-scale=1",
                    "format-detection": "telephone=no",
                }, ],
            },
        },
    ],
};